#!/usr/bin/env bash
# Displays:
#+ The content of the current directory,
#+ In a list format,
#+ Where only the part of the name after the first dash is displayed.

for files in *
do
	echo "$files" | cut -d- -f2
done
