#!/usr/bin/env bash
# This script will:
#+ Create the file /var/run/myscript.pid containing its PID
#+ Display To infinity and beyond indefinitely
#+ Display I hate the kill command when receiving a SIGTERM signal
#+ Display Y U no love me?! when receiving a SIGINT signal
#+ Delete the file /var/run/myscript.pid and terminates itself when receiving
#+ a SIGQUIT or SIGTERM signal

rmfile() { 
	rm -rf /var/run/myscript.pid
	exit
}

msgterm() {
	echo "I hate the kill command"
}

msgint() {
	echo "Y U no love me?!"
}
trap "msgterm; rmfile" SIGTERM
trap "msgint" SIGINT
trap "rmfile" SIGQUIT

echo $$ > /var/run/myscript.pid
while :
do
    echo "To infinity and beyond"
	sleep 0.5
done
