#!/usr/bin/env bash
# This script will manage /tmp/my_process file

on() {
	./manage_my_process & echo $! > /var/run/my_process.pid
}

off() {
	sudo pkill -f "./manage_my_process" & rm /var/run/my_process.pid
}

case $1 in
	start) on; echo "manage_my_process started";;
	stop) off; echo "manage_my_process stopped";;
	restart) off; on; echo "manage_my_process restarted";;
	*) echo "Usage: manage_my_process {start|stop|restart}";;
esac
