#!/usr/bin/env bash
# This script will manage /tmp/my_process file

start() {
	./manage_my_process & echo $! > /var/run/my_process.pid
}

stop() {
	sudo kill $(pgrep -f manage) & rm -rf /var/run/my_process.pid
}

case $1 in
	start) start; echo "manage_my_process started";;
	stop) stop; echo "manage_my_process stopped";;
esac
