#!/usr/bin/env bash
# This script will display:
#+ To infinity and beyond indefinitely with sleep 2
#+ I am invincible!!! when receiving a SIGTERM signal

trap "echo I am invincible!!!" SIGTERM
while :
do
	echo "To infinity and beyond"
	sleep 2
done
